/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author vayit
 */
public class VistaMenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuCliente
     */
    public VistaMenuCliente() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        lblBienvenida = new javax.swing.JLabel();
        btnComprar = new javax.swing.JToggleButton();
        btnMisEntradas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnMetodoPago = new javax.swing.JButton();
        btnPerfilCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Segoe UI Black", 2, 16)); // NOI18N
        lblBienvenida.setText("BIENVENIDO");
        getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ComprarEntradas.png"))); // NOI18N
        btnComprar.setText("Comprar Entradas");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 270, 30));

        btnMisEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MisEntradas.png"))); // NOI18N
        btnMisEntradas.setText("Mis Entradas");
        btnMisEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisEntradasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMisEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 270, 30));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cerrar sesión.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 120, 30));

        btnMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MetodoPago.png"))); // NOI18N
        btnMetodoPago.setText("Método de Pago");
        btnMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 270, 30));

        btnPerfilCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Miperfil.png"))); // NOI18N
        btnPerfilCliente.setText("Mi perfil");
        getContentPane().add(btnPerfilCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnMisEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMisEntradasActionPerformed

    private void btnMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodoPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JToggleButton btnComprar;
    public javax.swing.JButton btnMetodoPago;
    public javax.swing.JButton btnMisEntradas;
    public javax.swing.JButton btnPerfilCliente;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
