/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author flowxy
 */
public class VistaMenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName());

    /**
     * Creates new form VistaMenuAdmin
     */
    public VistaMenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        btnGenerarConcierto = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnGestionVentas = new javax.swing.JButton();
        btnGestionUsuarios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblBienvenida.setText("BIENVENIDO");
        getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        btnGenerarConcierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/GenerarConcierto.png"))); // NOI18N
        btnGenerarConcierto.setText("Generar Concierto");
        btnGenerarConcierto.addActionListener(this::btnGenerarConciertoActionPerformed);
        getContentPane().add(btnGenerarConcierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 190, 30));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cerrar sesión.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 126, 30));

        btnGestionVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/GestionVentas.png"))); // NOI18N
        btnGestionVentas.setText("Gestión de Ventas");
        btnGestionVentas.addActionListener(this::btnGestionVentasActionPerformed);
        getContentPane().add(btnGestionVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 190, 30));

        btnGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/GestionUsuarios.png"))); // NOI18N
        btnGestionUsuarios.setText("Gestión de Usuarios");
        getContentPane().add(btnGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU ADMINISTRADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MostrarConcierto.png"))); // NOI18N
        jButton1.setText("Mostrar Conciertos");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConciertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarConciertoActionPerformed

    private void btnGestionVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionVentasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnGenerarConcierto;
    public javax.swing.JButton btnGestionUsuarios;
    public javax.swing.JButton btnGestionVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
