/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class VistaCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCompra.class.getName());

    /**
     * Creates new form VistaCompra
     */
    public VistaCompra() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConcierto = new javax.swing.JLabel();
        lblZona = new javax.swing.JLabel();
        cboZona = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        lblMonto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumen = new javax.swing.JTextArea();
        txtNumeroTarjeta = new javax.swing.JTextField();
        txtNombreTarjeta = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        txtFechaTarjeta = new javax.swing.JTextField();
        cboConcierto = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConcierto.setText("CONCIERTO: ");
        getContentPane().add(lblConcierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblZona.setText("ZONA: ");
        getContentPane().add(lblZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        cboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Preferencial", "General", "Tribuna" }));
        getContentPane().add(cboZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        lblCantidad.setText("CANTIDAD:");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        getContentPane().add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        lblMonto.setText("MONTO:         S/ 0.0");
        getContentPane().add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 109, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("DATOS DE TARJETA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel2.setText("Número: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 50, -1));

        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 49, -1));

        jLabel5.setText("CVV:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 37, -1));

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra.png"))); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(this::btnComprarActionPerformed);
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, 40));

        jLabel7.setText("Resumen:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 59, -1));

        txtResumen.setColumns(20);
        txtResumen.setRows(5);
        jScrollPane1.setViewportView(txtResumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 270, 130));
        getContentPane().add(txtNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 150, -1));
        getContentPane().add(txtNombreTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, -1));
        getContentPane().add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 150, -1));

        txtFechaTarjeta.addActionListener(this::txtFechaTarjetaActionPerformed);
        getContentPane().add(txtFechaTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 150, -1));

        cboConcierto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboConcierto.addActionListener(this::cboConciertoActionPerformed);
        getContentPane().add(cboConcierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("COMPRA DE ENTRADAS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtFechaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTarjetaActionPerformed

    private void cboConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboConciertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboConciertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComprar;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cboConcierto;
    public javax.swing.JComboBox<String> cboZona;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCantidad;
    public javax.swing.JLabel lblConcierto;
    public javax.swing.JLabel lblMonto;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblZona;
    public javax.swing.JSpinner spnCantidad;
    public javax.swing.JTextField txtCvv;
    public javax.swing.JTextField txtFechaTarjeta;
    public javax.swing.JTextField txtNombreTarjeta;
    public javax.swing.JTextField txtNumeroTarjeta;
    public javax.swing.JTextArea txtResumen;
    // End of variables declaration//GEN-END:variables
}
